name: Localize
on: [ release, workflow_dispatch ]
jobs: 

  job-1: #nombre del job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run action-localizable
        uses: viavansi/github-actions/action-localize@1
