name: private
on: [ release, workflow_dispatch ]
jobs: 

  job-1: #nombre del job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: acalderon-dvp/Repositorio2@main
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN}}
        
      - name: Uso de accion
        uses: ./
        
        
  #job-2:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Run action-localizable
  #      uses: viavansi/github-actions/action-localize@v1
        #with:
        #  repository: viavansi/github-actions
        #  token: ${{ secrets.PRIVATE_ACCESS_TOKEN_FOR_ACTIONS }}
