name: Localize
on: [ release, workflow_dispatch ]
jobs: 

  job-java: #nombre del job
    runs-on: [ windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: viavansi/github-actions/action-localize
          token: ${{secrets.PRIVATE_ACCESS_TOKEN_FOR_ACTIONS}}
        
      - name: Run action-localize
        uses: ./action-localize
