name: public
on: [ workflow_dispatch ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: paso1
        uses: acalderon-dvp/actions@v1

      - name: paso2
        run: echo 'Hello desde el workflow'
        shell: bash
